= Техническое задание: инженерно-геодезические изыскания методом цифровой аэрофотосъемки
:author: Максим Гришкин
:email: FFFFF@bk.ru
:revnumber: 0.1
:revdate: 29.04.2019
:revremark: Аппробированная версия
:description: Техническое задание на выполнение аэросъемки с беспилотных летательных аппаратов
:keywords: аэросъемка, БПЛА, техническое задание, ТЗ, геодезия

// Путь к файлам данных
:datadir: ./data  

// Нумерация секций
:sectnums:

== Общие сведения

[cols="2,8"]
[width="100%"]
[format=csv]
|====================
include::{datadir}/contragents.csv[]
|====================


.Описание объектов работ

[caption=""]
[cols="^1,3,10"]
[options="header"]
[width="100%"]
[%header,format=csv]
|====================
include::{datadir}/object.csv[]
|====================

.Цель выполнения работ
Использование результатов работ при мониторинге текущих изменений территории, проведении землеустроительных и кадастровых работ, инвентаризации объектов недвижимости, инженерно-геодезических изысканиях. 


== Виды и содержание работ

. Подготовительные работы:
.. Получение разрешений для выполнения работ в Генеральном Штабе, Штабе военного округа и ФСБ России;
.. Получение каталогов координат пунктов ГГС.
. Полевые работы:
.. Рекогносцировка местности;
.. Создание опорной геодезической сети для обеспечения аэросъёмочных работ и дальнейшего сгущения;
.. Геодезическое обеспечение аэросъёмочных работ;
.. Аэросъёмочные работы;
.. Контроль и приёмка полевых работ.
. Камеральная обработка аэросъёмочных материалов:
.. Создание цифровой модели местности (ЦММ или DSM) в виде облака точек;
.. Автоматическая классификация облака точек;
.. Создание ортофотопланов;
.. Создание текстурированных полигональных моделей местности на основании разреженного облака точек;
.. Создание текстурированных полигональных моделей объектов капитального строительства на основании плотного облака точек;
.. Контроль и приёмка камеральных работ.
. Предоставление материалов аэрофотосъёмки на контрольный просмотр в штаб военного округа.
. Рассекречивание материалов, передаваемых Заказчику (при необходимости).
. Создание технического отчёта.
. Сдача-приёмка выполненных работ Заказчику.
. Предоставление Заказчику доступа к Геопорталe:
.. Размещение в сети Интернет текстурированных полигональных моделей местности на Геопортале Подрядчика;
.. Предоставление доступа Заказчику к Геопорталу с возможностью просмотра, анализа, редактирования и добавления векторных и данных и текстурированных полигональных моделей;
.. Обеспечение Заказчику возможности загрузки дополнительных векторных слоев (формат Esri Shape, kml) общим объёмом до 500 МБ;
.. Обеспечение Заказчику возможности загрузки дополнительных полигональных моделей местности объёмом до 5 ГБ;
.. Обеспечение доступа Заказчика к Геопорталу в течение 3 лет.

== Контроль качества выполнения работ
. Качественное выполнение работ -- это выполнение работ с применением технологий, обеспечивающих наличие у произведённой продукции (оказанной услуги) совокупности свойств и характеристик, придающих продукции (услуге) способность удовлетворять обусловленные или предполагаемые потребности Заказчика. При этом работы должны выполняться в соответствии с действующими нормативно-правовыми актами, договором и настоящим техническим заданием.
. Подрядчик несёт полную ответственность за качество выполнения работ.
. С целью обеспечения качественного выполнения работ Подрядчик обязан осуществлять непрерывный технический и приёмочный контроль работ последовательно по всем звеньям структуры предприятия от исполнителя до отдела технического контроля.
. Заказчик может проводить выборочный контроль качества выполнения полевых и камеральных работ  с помощью оборудования, программного обеспечения и работников Подрядчика.
. Заказчик может участвовать в контроле качества выполнения работ Подрядчиком непосредственно или воспользовавшись услугами сторонних организаций.
. Заказчик при приёмке работ вправе уведомить Подрядчика о необходимости осуществления инструментального контроля:  
.. В ходе инструментального контроля определяется местоположение контрольных точек. Число контрольных точек не ограничивается;
.. Подрядчик обязан по согласованию с Заказчиком направить своих представителей вместе с необходимым геодезическим оборудованием для совместного выполнения контрольных измерений;
.. Контрольные измерения по решению Заказчика выполняются методами спутниковых геодезических измерений и/или тахеометрической съёмки;
.. По результатам контрольных измерений Подрядчик обязан передать Заказчику журналы измерений и результаты их обработки;
.. Срок приёмки работ в данном случае продляется на срок выполнения и обработки контрольных измерений.
. Объём и порядок участия Заказчика в контроле качества выполнения работ определяется Заказчиком дополнительно.


== Сроки выполнения работ
[cols="^1,5,8,2"]
[width="100%",options="header"]
|====================
| № | Наименование вида работ | Событие, определяющее начало выполнения работ | Срок, рабочих дней 
| 1 | Подготовительные работы | Подписание договора | 20 
| 2 | Полевые работы | Определяется Заказчиком дополнительно с учётом наиболее благоприятных для выполнения аэрофотосъёмки погодных условий  | 15 
| 3 | Камеральные работы | Завершение полевых работ | 15 
| 4 | Предоставление и контрольный просмотр материалов аэрофотосъёмки | Завершение камеральных работ | 25 
| 5 | Рассекречивание материалов (при необходимости) | Получение заключения о наличии сведений, составляющих государственную тайну | 20 
| 6 | Создание технического отчёта | Рассекречивание материалов | 5 
| 7 | Предоставление Заказчику доступа к Геопорталe | Создание технического отчёта | 5 
|====================

== Выходная продукция

В результате выполнения работ подрядчик передаёт Заказчику:

. Ортофотопланы;
. Облако точек;
. Текстурированные полигональные модели местности;
. Текстурированные полигональные модели объектов капитального строительства;
. Технический отчёт;
. Документ, подтверждающий возможность открытого опубликования картографической продукции;
. Учетные записи для доступа к Геопорталу.

.Требования к выходной продукции:
[caption=""]
[cols="^1,5,12"]
[options="header"]
[width="100%",options="header"]
|====================
| № | Вид продукции | Требования 
| 1 | Картографическая продукция в целом
a| 
. Не должна содержать сведения, отнесённые в установленном порядке, к государственной тайне. Должно быть разрешено открытое опубликование;
. Разграфка прямоугольная для масштаба 1:1000 с размерами сторон 0.5 × 0.5 км на местности;
. Система координат -- местная система координат кадастрового округа (МСК);
. Система высот -- Балтийская 1977 года.

| 2 | Ортофотопланы 
a|
. Предоставляются в электронном виде с разбивкой на листы в соответствии с системой разграфки;
. Формат GeoTiff с файлом привязки TFW, сжатие без потерь, размер пикселя -- 0,10 × 0,10 м, построенные пирамидные слои;
. Средняя квадратическая погрешность в плановом положении наземных объектов -- не хуже 0,20 м;
. Допускается наличие смещений крыш домов и крон деревьев, так как указанные объекты не являются наземными;
. Формируются в соответствии с требованиями инструкции по производству фотограмметрических работ ГКИНП (ГНТА)-02-036-02.
| 3 | Облако точек 
a| 
. Предоставляются в электронном виде с разбивкой на листы в соответствии с системой разграфки;
. Формат набор данных LAS.
. Средняя квадратическая погрешность положения точек в районе опознаков (в плане и по высоте) -- не хуже 0,20 м;
. Плотность облака точек не менее 10 точек/кв. м

| 4 | Общие требования к текстурированным полигональным моделям 
a|
. Предоставляются в электронном виде с разбивкой на листы в соответствии с системой разграфки;
. Объём модели до 300 тыс. полигонов;
. Формат Collada (*.DAE, *.JPG);
. Точность моделей должна соответствовать автоматическому построению (допускаются огрехи и искажения, требующие исправления «вручную»);
. Модели должны выглядеть фотореалистично, допускаются «слепые» зоны;
. Должены поддерживаться импорт в ArcGis ArcMap в автоматическом режиме.

| 5 | Текстурированные полигональные модели местности | Init 
| 6 | Текстурированные полигональные модели объектов капитального строительства 
a| 
. Cредняя квадратическая погрешность положения элементов модели (в плане и по высоте) у их основания  – не хуже 50 см.
| 7 | Технический отчёт 
a| 
. Технический отчёт по инженерным изысканиям должен соответствовать требованиям СНиП 11-02-96 (актуализированная редакция СП47.13330.2012);
. Допустимые форматы: 
.. электронных образовов документов: pdf, djvu;
.. векторных графических файлов: dwg/dxf, MapInfo tab, MapInfo mif/mid, Esri Shape;
.. растровых графических файлов: GeoTiff, jpg, ecw;
.. файлов c табличными данными: csv, xls (Microsoft Excel), ods (OpenDocument);
.. текстовых файлов: Markdown, AsciiDoc, ReStructuredtext, doc (Microsoft Word), odt (OpenDocument).
| 8 | Документ, подтверждающий возможность открытого опубликования картографической продукции
| Предоставляется в виде оригинала в бумажном виде, а также в виде электронного образа докумета.
| 9 | Учетные записи для доступа к Геопорталу
a| 
. Учетная запись с правом редактировать данные;
. Учетные запись только для просмотра.
|====================


