= Требования к наземному геодезическому обеспечению аэросъёмочных работ:

. Допуск работников Подрядчика на объект согласовывается с Заказчиком;
. Определение и закрепление планово-высотных опознавательных знаков (ОПВ) -- не менее 8 штук, равномерно распределённых по территории объекта;
. Точность определения координат ОПВ -- не хуже 0,05 м в плане и по высоте.


= Требования к выполнению аэросъёмочных работ:

. Выполняются при:
[disc]
  * углах солнца не менее 15 градусов над горизонтом;
  * отсутствии снежного покрова на площади более 80% (при возможности);
  * минимальной вегетации растительности (при возможности);
  * скорости ветра не более 15 м/с; 
  * отсутствии атмосферных осадков; 
  * облачности выше высоты аэрофотосъёмки. Наличие теней от облаков допускается;
  * отсутствии иных факторов, мешающих качественному проведению аэросъёмочных работ.
. Аэросъёмочная аппаратура должна быть откалибрована (подтверждается сертификатом калибровки);
. Аэросъёмочная аппаратура должна обеспечивать компенсацию оптического сдвига («смаза») изображения, как вследствие линейного перемещения воздушного судна, так и вследствие его угловых колебаний. Максимальный смаз фотоизображения -- не более 1 пикселя;
. Не допускается наличие продольных и поперечных разрывов изображения;
. Размер стороны пикселя аэроснимка на земле (GSD) -- не более 0,10 м;
. Продольное перекрытие между снимками не менее 70%;
. Поперечное перекрытие между снимками не менее 50%.