= Цифровая модель ситуации и рельефа

. Цифровая модель ситуации и рельефа (модель) -- логико-математическое представление в цифровой форме физических (местоположение, длина, ширина, высота, материал и т.д.) и функциональных (назначение, мощность и т.д.) характеристик местности и рельефа при помощи совокупности геометрических элементов (полилиний, полигонов, точек, поверхностей и т.д.), связанной с ними семантической (информация о непространственных характеристиках) и топологической (информация о связности и соседстве объектов и их частей) информации;
. Информационное наполнение модели структурируется в реляционную модель данных, состоящую из набора таблиц. Таблицы, содержащие пространственный столбец (атрибут) могут называться слоями;
. Модель ситуации подготавливается в формате совместимом с ГИС ArcGis (ArcGis Shape file, файловой базы геоданных ArcGis, базы данных MS SQL Server (MS SQL Server 2014 (*.mdf и *.ldf), тип пространственных данных Geometry) и т.д.);
. Модель рельефа подготавливается в виде регулярной сетки в формате GeoTiff;
. Модель не должна содержать элементы, связанные с оформлением чертежей (штампы, зарамочное оформление);
. Информация, отражающая сущность и характеристики элементов модели (семантическая информация), вносится в атрибуты (столбцы) слоёв (таблиц), в том числе связанных слоёв (таблиц);
. Каждая таблица должна иметь первичный ключ, обеспечивающий уникальную идентификацию каждой строки таблицы;
. Все данные должны быть согласованны друг с другом, должна обеспечиваться целостность данных, а также внутренняя непротиворечивость;
. При заполнении таблиц повторяющимися значениями должны использоваться справочники (специальные таблицы). В таблице, использующей справочники, должен быть атрибутивный столбец, содержащий внешний ключ на первичный ключ справочника;
. Однотипные объекты должны содержаться в одном слое. Например, слой трубопроводы может содержать водопроводы, газопроводы и т.д. Для различения отдельных подтипов объектов используется столбец-дискриминатор;
. Геометрическая составляющая элементов должна быть выполнена в местной системе координат кадастрового округа, система высот Балтийская;
. Все пространственные данные должны иметь топологическую (метрическую) корректность (согласованность) данных как внутри слоя, так и между слоями;
. Каждый слой должен содержать только объекты одного типа геометрической формы (полигоны, полилинии, точки), за исключением случая, если внутренний формат хранения модели поддерживает разделение по типу геометрии стандартными средствами (например, базы данных MS SQL Server);
. Единый линейный элемент модели не может состоять из отдельных, но имеющих общие точки отрезков;
. Выноски и др. поясняющие надписи. местоположение которых должно быть фиксировано. размещаются в отдельных слоях-аннотациях и дублируются в атрибутивной информации объектов;
. Формат и структура модели согласовывается Заказчиком дополнительно на основе подготовленных Подрядчиком предложений.

= Электронная карта в формате ГИС Esri ArcGis
. Электронная карта подготавливается в формате Esri ArcGis mxd версии от 10.0 до 10.5;
. Картографическое содержание отображается в условных знаках в соответствии с условными знаками для топографических планов масштабов 1:5000, 1:2000, 1:1000, 1:500 (утверждены ГУГК при Совете Министров СССР 25 ноября 1986 г.);
. Отображение условных знаков различных типов объектов слоя осуществляется с использованием инструмента Символы\Категории;
. Для оптимизации производительности могут использоваться слои-аннотации вместо инструментов подписывания карты;
. Разделение на листы не производится;
. Слои объединяются в группы слоев.

= Электронная версия графических чертежей в формате САПР
. Графические чертежи подготавливаются на основе цифровой картографической модели ситуации и рельефа (модель);
. Слои модели могут отображаться на один или несколько слоев чертежа в формате САПР (слои САПР) в соответствии с Кодификатором ГУГК 1 : 500;
. Как правило свойства графического отображения объектов (цвет, толщина линии, прозрачность) должны задаваться на уровне всего слоя, а не отдельных объектов.

= Классификатор пространственных объектов цифровой модели ситуации и рельефа
. Классификатор пространственных объектов цифровой модели ситуации и рельефа включает перечень таблиц (слоев), столбцов (атрибутов), справочников, а также условных знаков;
. Подрядчик самостоятельно разрабатывает классификатор пространственных объектов и согласовывает его с Заказчиком. В ходе выполнения работ Подрядчик может по согласованию с Заказчиком вносить в него изменения;
. Подрядчик передает используемые при оформлении электронной карты в формате ГИС Esri ArcGis условные знаки в файле формата .style, шрифты в формате .ttf;
. Примерный перечень таблиц (слоев):
  .. Геодезические пункты;
  .. Гидрография;
  .. Горизонтали;
  .. Границы;
  .. Грунты и покрытия;
  .. Дороги;
  .. Кабели;
  .. Колодцы;
  .. Ограждения;
  .. Отметки высот;
  .. Постройки;
  .. Растительность;
  .. Рельеф;
  .. Сетка;
  .. Сооружения;
  .. Топонимика;
  .. Трубопроводы.
