// Требования к выполняемым работам

= Требования к полевым геодезическим работа:

. Допуск работников Подрядчика на объект согласовывается с Заказчиком.
. Средние квадратические погрешности определения планового положения предметов и контуров местности с четкими, легко распознаваемыми очертаниями (границами) относительно ближайших пунктов государственных геодезических сетей, не должны превышать 0,1 м.
. Средние квадратические погрешности в плановом положении точек подземных коммуникаций и сооружений относительно ближайших капитальных зданий (сооружений) и точек съемочного обоснования не должны превышать 0,4 м.


= Требования к кадастровым работам:

Установление границ земельного участка на местности осуществляется в случае, если при согласовании местоположения границ заинтересованное лицо потребовало согласования местоположения границ с их установлением на местности:

. Поворотные точки границ земельного участка закрепляют временными межевыми знаками:
[disc]
* Временные межевые знаки изготавливают из деревянных брусков или металлических прутьев арматуры высотой от 700 мм, диаметром от 5 мм;
* Временный межевой знак, закрепляемый в твердую поверхность (бетон, камень), выполняется в виде металлического дюбеля;
* Временный межевой знак, закрепляемый в стене здания, может быть выполнен в виде вертикальной откраски;
* Временный межевой знак выделяется яркой лентой и (или) окраской.
. Поворотные точки границ, совпадающих с четкими, легко распознаваемыми очертаниями (границами) контуров местности, можно обозначать краской или яркой лентой и не закреплять временными межевыми знаками.



